((connections . ((n000 . ("n001"))
                 (n001 . ())))
 (nodes       . ((n000 . ((hostname . "localhost")
                          (port     . 11000)))
                 (n001 . ((hostname . "localhost")
                          (port     . 11001)))
                )))
