((connections . ((n000 . ("n001"))
                 (n001 . ())))
 (nodes       . ((n000 . ((hostname . "n000.default.svc.cluster.local")
                          (port     . 11000)))
                 (n001 . ((hostname . "n001.default.svc.cluster.local")
                          (port     . 11000)))
                )))
